### ISSUE TITLE
🐞 Introducing a light/dark mode feature. 

### ISSUE THREAD

**Issue by PranjalGupta22** [5t3ph/stylestage#188]
**Issue Description**

Our project's website is undoubtedly functional and informative, but it's time to take it a step further by adding some interactive elements. I propose enhancing the website design with subtle hovering effects to create a more engaging and interactive user experience. Additionally, introducing a light/dark mode feature is increasingly crucial in today's web design, catering to users' preferences and comfort.

This website is a valuable, functional, and informative platform, but there's room for improvement in the design department. To enhance user experience, I propose introducing a light/dark mode feature and the addition of some interactive effects to the pages. Both these design elements have become crucial, as they make the website more engaging, accessible, and user-friendly.

**Screenshot**

![image](https://github.com/5t3ph/stylestage/assets/123003273/f419a236-8aab-4b19-8cdd-406586070ad8)

✅I would like to work on this issue.

**Comment by Tushar-Sahu7** [comment]
@PranjalGupta22 I would like to work on this issue.

**Comment by 5t3ph** [comment]
Sorry, this is not an issue I'm looking for a contributor for.
