### ISSUE TITLE
Probable unnecessary H2 

### ISSUE THREAD

**Issue by hankchizljaw** [5t3ph/stylestage#5]
I'd say a paragraph with a style hook or nth-child selector is more appropriate here: https://github.com/5t3ph/stylestage/blob/8615f7b394947220a8fca0754a40a19b8bd870f2/src/_includes/html.njk#L6

**Comment by 5t3ph** [comment]
I will have to think about how to make this update since I'm expecting a batch of styles today that might be hooked to it, but I agree!

**Comment by hankchizljaw** [comment]
It's certainly not a showstopper-more a small improvement 🙂
