### ISSUE TITLE
What is the licence of this repo?

### ISSUE THREAD

**Issue by gusbemacbe** [5t3ph/stylestage#90]
Hello!

– What is this licence of this repo?
– I do not understand "Contributors retain copyright of all graphics used, and **styles are available under CC BY-NC-SA**". Do you mean that the CSS styles can not be used for the commercial sites?

**Comment by 5t3ph** [comment]
Hi @gusbemacbe - the repo is under the same license as the styles - https://creativecommons.org/licenses/by-nc-sa/3.0/

And yes, that is correct - you should not just lift the exact designs and use them in their entirety for commercial gain. You can learn from them and use some ideas or some CSS techniques, but for example you should not take an entire design as is and turn it into a sellable WordPress theme or provide it as an original idea that you sell to a freelance client.
